# Generated by Django 5.2.5 on 2025-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_assignees'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='uniq_project_team_name'),
        ),
    ]
