# Generated by Django 5.2.5 on 2025-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_task_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='uniq_project_team_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('team', 'name')},
        ),
    ]
